### ISSUE TITLE
OverB0ard

### ISSUE THREAD

**Issue by klaix** [Doregon/overb0ard#1]
Hi Good Day!

I just noticed that it doesn’t work on PUBG and I’m curious why it doesn’t work and what security or method it used.

**Comment by Doregon** [comment]
What do you mean "doesn't work"? How were you going about using overb0ard?

**Comment by klaix** [comment]
Just the usual way (command -l MEM appname)

It says that “no such process” I’ve even use upmem similar to this.

**Comment by Doregon** [comment]
upmem is a wrapper script around overb0ard which sorts through the process names. These names are, in some cases, different from the application name and such you must find the process name first.

1. Open Filza and navigate to /var/containers/Bundle (for App Store apps) or /Applications (apps you can't delete or jailbreak apps) and tap into the folder of the app you wish to edit. 

2. Open `Info.plist` and look for `CFExecutableName`. The entry for that is what you want to put into the jetsamctl command.

**Comment by klaix** [comment]
I have tried it, still does not work on PUBG MOBILE. I’m wondering why it does not work on this application while most of the other apps works flawlessly.

**Comment by Doregon** [comment]
> I’ve even use upmem similar to this.

So upmem worked?

**Comment by klaix** [comment]
No, it doesn’t work.

**Comment by Doregon** [comment]
What's the process name?

**Comment by klaix** [comment]
ShadowTrackerExtra, I don’t know why it says like that on PUBG and it caught my attention.

**Comment by Doregon** [comment]
It must be an issue with just PUBG, I can't do testing because my 16GB iPhone doesn't have enough storage to install the game :/
