### ISSUE TITLE
App crash after 3 secs

### ISSUE THREAD

**Issue by iCosy** [Doregon/overb0ard#4]
I tried 1000 and 500 same result. I reboot retried same result
![image](https://user-images.githubusercontent.com/36975658/120115024-db415080-c14f-11eb-9c1e-c35c48fc4108.png)

**Comment by iCosy** [comment]
![image](https://user-images.githubusercontent.com/36975658/120115187-8f42db80-c150-11eb-8e21-a974442f93fc.png)

**Comment by iCosy** [comment]
![image](https://user-images.githubusercontent.com/36975658/120115199-979b1680-c150-11eb-8378-f74224b931c5.png)
![image](https://user-images.githubusercontent.com/36975658/120115206-9bc73400-c150-11eb-9950-197df29751d4.png)

**Comment by iCosy** [comment]
So now I play in safe mode. Sorry for multiple comments page

**Comment by Doregon** [comment]
Wait so it’s crashing even when you don’t run the command?

**Comment by iCosy** [comment]
> Wait so it’s crashing even when you don’t run the command?

Yes

**Comment by iCosy** [comment]
May be others tweaks. I think. Thanks for you time. I closed

**Comment by Doregon** [comment]
Oh sorry I didn’t get back to you, I’ve been busy with other things. i do believe that it’s another tweak as you said because overb0ard doesn’t make permanent changes to the jetsam settings.
